import type { Metadata } from "next";

import {Cairo} from 'next/font/google'
import "./globals.css";
import { UserProvider } from "./UserContext";
const cairo = Cairo({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap', 
 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="ar">
      <body
        style={{
          direction:'rtl',
        }}
        className={`${cairo.className} antialiased  `}
      >
        <UserProvider>

        {children}
        </UserProvider>
      </body>
    </html>
  );
}
